name: prechecks

on:
  workflow_call:
    inputs:
      with_coverage:
        required: true
        type: string
      with_packages:
        required: true
        type: string

concurrency:
  group: style-${{github.ref}}-${{github.event.pull_request.number || github.run_number}}
  cancel-in-progress: true


jobs:
  # Validate that the code can be run on all the Python versions supported by Spack
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b
      with:
        python-version: '3.13'
    - name: Install Python Packages
      run: |
        pip install -r .github/workflows/requirements/style/requirements.txt
    - name: vermin
      run: |
        vermin --backport importlib \
               --backport argparse \
               --violations \
               --backport typing \
               -t=3.6- \
               -vvv \
               --exclude-regex lib/spack/spack/vendor \
               lib/spack/spack/ lib/spack/llnl/ bin/ var/spack/test_repos

  # Run style checks on the files that have been changed
  style:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      with:
        fetch-depth: 2
    - uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b
      with:
        python-version: '3.13'
    - name: Install Python packages
      run: |
        pip install -r .github/workflows/requirements/style/requirements.txt
    - name: Run style tests (code)
      run: |
        bin/spack style --base HEAD^1
        bin/spack license verify
        pylint -j $(nproc) --disable=all --enable=unspecified-encoding --ignore-paths=lib/spack/spack/vendor lib
    - name: Run style tests (docs)
      run: bin/spack python .github/workflows/bin/format-rst.py $(git ls-files 'lib/spack/docs/*.rst')


  # Check that spack can bootstrap the development environment on Python 3.6 - RHEL8
  bootstrap-dev-rhel8:
    runs-on: ubuntu-latest
    container: registry.access.redhat.com/ubi8/ubi
    steps:
      - name: Install dependencies
        run: |
          dnf install -y \
              bzip2 curl file gcc-c++ gcc gcc-gfortran git gnupg2 gzip \
              make patch tcl unzip which xz
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Setup repo and non-root user
        run: |
          git --version
          git config --global --add safe.directory '*'
          git fetch --unshallow
          . .github/workflows/bin/setup_git.sh
          useradd spack-test
          chown -R spack-test .
      - name: Bootstrap Spack development environment
        shell: runuser -u spack-test -- bash {0}
        run: |
          source share/spack/setup-env.sh
          spack debug report
          spack -d bootstrap now --dev
          spack -d style -t black
          spack unit-test -V

  canonicalization:
    name: package.py canonicalization
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/spack/all-pythons:2025-07-25

    steps:
      - name: Checkout Spack (current)
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          path: spack-current
      - name: Checkout Spack (previous)
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          path: spack-previous
          ref: ${{ github.event.pull_request.base.sha || github.event.before }}
      - name: Checkout Spack Packages
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          repository: spack/spack-packages
          path: spack-packages
      - name: Test package.py canonicalization
        run: spack-current/.github/workflows/bin/canonicalize.py
          --spack $PWD/spack-previous $PWD/spack-current
          --python python3.6 python3.7 python3.8 python3.9 python3.10 python3.11 python3.12 python3.13
          --input-dir spack-packages/repos/spack_repo/builtin/packages/
          --output-dir canonicalized
